image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - cd doc/
  - hugo
  except:
  - master

before_script:
- git submodule init
- git submodule update --force

pages:
  script:
  - mkdir -p /tmp/public
  - cd src && hugo -d /tmp/public && cd -
  - mv /tmp/public/index.html /tmp/public/doc.html
  - cp -r * /tmp/public/
  - rm -rf /tmp/public/src
  - mv /tmp/public .
  artifacts:
    paths:
    - public
  only:
  - master
