image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - cd doc/
  - hugo
  except:
  - master

before_script:
- git submodule init
- git submodule update --force

pages:
  script:
  - sudo apt install rsync
  - mkdir -p public
  - cd src && hugo -d ../public && cd -
  - mv public/index.html public/doc.html
  - rsync -a * public --exclude src --exclude public
  artifacts:
    paths:
    - public
  only:
  - master
