language: generic

dist: trusty
sudo: false

services:
  - docker

branches:
  only:
  - master
  - ci-cd
  - /v(\d+\.)(\d)/

env:
  global:
    - SWARM_VERSION=v0.3.11
    - SWARM_BZZ_API=https://swarm-public-staging.stg.swarm-gateways.net/

stages:
  - name: release
    if: tag IS present
  - name: deploy
    if: tag IS present

before_script:
  - export RELEASE_FILE="swarm-home-$TRAVIS_TAG.zip"
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"

jobs:
  include:
    - stage: release
      script: echo "Deploying to GitHub releases ..."
      before_deploy:
        - git archive -o $RELEASE_FILE -9 HEAD
      deploy:
        provider: releases
        api_key: "$RELEASE_OAUTH_TOKEN"
        file: "$RELEASE_FILE"
        skip_cleanup: true
        on:
          all_branches: true
          tags: true

    - stage: deploy
      script:
        - wget https://github.com/ethersphere/swarm-home/releases/download/$TRAVIS_TAG/$RELEASE_FILE
        - mkdir .release && unzip -v -d .release $RELEASE_FILE
        - ls -la .release
        - docker pull ethdevops/swarm:$SWARM_VERSION
        - >-
          export HASH=$(docker run --rm -it --entrypoint /swarm
          -v $PWD/.release:/release
          -v /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
          ethdevops/swarm:$SWARM_VERSION
          --bzzapi $SWARM_BZZ_API
          --defaultpath /release/index.html
          --recursive up /release)
        - "echo \"Uploaded sucessfully to swarm: $HASH\""
